accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.myAccount),
    path("register-user/", views.registerUser, name="register-user"),
    path("register-vendor/", views.registerVendor, name="register-vendor"),
    path("login/", views.user_login, name="user-login"),
    path("logout/", views.user_logout, name="user-logout"),
    path("myAccount/", views.myAccount, name="my-account"),
    path("customer-dashboard/", views.custDashboard, name="customer-dashboard"),
    path("vendor-dashboard/", views.venDashboard, name="vendor-dashboard"),

    #email Verification
    path('activate/<uidb64>/<token>/', views.activate_account, name="activate"),

    #Forgot Password Links
    path('forgot-password/', views.forgot_password, name="forgot-password"),
    path('reset-password-validate/<uidb64>/<token>/', views.reset_password_validate, name="reset-password-validate"),
    path('reset-password/', views.reset_password, name="reset-password"),

    #Vendor Path
    path('vendor/', include('vendor.urls'), name="vendor"),
]

foodOnline_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as marketplaceviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('', include('accounts.urls'), name="accounts"),
    path('marketplace/', include('marketplace.urls'), name="marketplace"),
    path('cart/', marketplaceviews.cart, name="cart"),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self, first_name, last_name, email, username, password=None):
        if not email:
            raise ValueError("User must have an email")
        if not username:
            raise ValueError("User must have a username")
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, first_name, last_name, email, username, password=None):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
            password = password,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user
    
class User(AbstractBaseUser):
    RESTAURANT = 1
    CUSTOMER = 2

    ROLE_CHOICE = (
        (RESTAURANT, "Restaurant"),
        (CUSTOMER, "Customer"),
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100, unique=True)
    username = models.CharField(max_length=50, unique=True)
    phone_number = models.CharField(max_length=14, blank=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICE, blank=True, null=True)

    # Required Fields
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now = True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "first_name", "last_name"]

    objects = UserManager()

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True
    
    def get_role(self):
        if self.role == 1:
            user_role = 'Restaurant'
        elif self.role == 2:
            user_role = 'Customer'
        return user_role
             

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    profile_pictures = models.ImageField(upload_to="users/profile-pictures", null=True, blank=True)
    cover_photo = models.ImageField(upload_to="users/cover-photo", null=True, blank=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    country = models.CharField(max_length=15, blank=True, null=True)
    state = models.CharField(max_length=20, blank=True, null=True)
    city = models.CharField(max_length=20, blank=True, null=True)
    pin_code = models.CharField(max_length=6, null=True, blank=True)
    latitude = models.CharField(max_length=20, null=True, blank=True)
    longitude = models.CharField(max_length=20, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.user.email

accounts/forms.py
from django import forms
from .models import User, UserProfile
from .validators import only_image_validator

class RegisterUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ["email", "username", "first_name", "last_name", "phone_number", "password"]

    def clean(self):
        cleaned_data = super(RegisterUserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("Password Didn't Match!")
        
class UserProfileForm(forms.ModelForm):
    address= forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Start Typing.....", "required":"required"}))
    profile_pictures = forms.FileField(widget=forms.FileInput(attrs={"class":"btn btn-info"}), validators=[only_image_validator])
    cover_photo = forms.FileField(widget=forms.FileInput(attrs={"class":"btn btn-info"}), validators=[only_image_validator])
    class Meta:
        model = UserProfile
        fields = ['profile_pictures','cover_photo', 'address', 'country', 'state', 'city', 'pin_code', 'latitude', 'longitude'] 

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if field == 'longitude' or field == "latitude":
                self.fields[field].widget.attrs['readonly'] = 'readonly'

accounts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import auth
from .forms import RegisterUserForm
from .models import User, UserProfile
from vendor.forms import VendorForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from .utils import detectUser, send_email_verification
from django.core.exceptions import PermissionDenied
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from vendor.models import Vendor
from django.template.defaultfilters import slugify

#Restrict vendor from accessing the Customer Dashboard
def detect_vendor_user(user):
    if user.role == 1:
        return True
    else:
        raise PermissionDenied

#Return customer from accessing the Vendor Dashboard
def detect_customer_user(user):
    if user.role == 2:
        return True
    else:
        raise PermissionDenied

def registerUser(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are already logged In!")
        return redirect("accounts:my-account")
    
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            #**Django Form**

            password = form.cleaned_data['password']
            user = form.save(commit=False)
            user.set_password(password)
            user.role = User.CUSTOMER
            user.save()
            #email verification
            try:
                mail_subject = 'Please verify your Account'
                email_template = 'accounts/emails/account-verification.html'
                send_email_verification(request, user, mail_subject, email_template)
            except Exception as e:
                messages.error(request, f"{e}")
            messages.success(request, "User Registered Successfully!")
            return redirect("accounts:register-user")

            #**Create Objects**
            # first_name = form.cleaned_data['first_name']
            # last_name = form.cleaned_data['last_name']
            # email = form.cleaned_data['email']
            # phone_number = form.cleaned_data['phone_number']
            # username = form.cleaned_data['username']
            # password = form.cleaned_data['password']
            # user = User.objects.create(first_name=first_name, last_name=last_name, username=username, email=email, phone_number=phone_number, password=password)
            # user.role = User.CUSTOMER
            # user.save()
            # return redirect("accounts:register-user")
        # else:
        #     print(form.errors)
    else:
        form = RegisterUserForm()
    context = {
        "form" : form,
    }
    return render(request, "accounts/register-user.html", context)

def registerVendor(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are already logged In!")
        return redirect("accounts:my-account")
    
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        v_form = VendorForm(request.POST, request.FILES)
        if form.is_valid() and v_form.is_valid():
            password = form.cleaned_data['password']
            user = form.save(commit=False)
            user.set_password(password)
            user.role = User.RESTAURANT
            user.save()
            vendor = v_form.save(commit=False)
            vendor.user = user
            vendor_name = v_form.cleaned_data['vendor_name']
            vendor.vendor_slug = slugify(vendor_name)+"-"+str(user.id)
            user_profile = get_object_or_404(UserProfile, user=user)
            vendor.user_profile = user_profile
            vendor.save()
            #email Verification
            try:
                mail_subject = 'Please verify your Account'
                email_template = 'accounts/emails/account-verification.html'
                send_email_verification(request, user, mail_subject, email_template)
            except Exception as e:
                messages.error(request, f"{e}")
            messages.success(request, "Your Account Has been Registered! Please wait for Approval")
            return redirect("accounts:register-vendor")
        else:
            messages.error(request, "Error!! Please Fill the form Again!")
    else:
        form = RegisterUserForm()
        v_form = VendorForm()
    context = {
        "form" : form,
        "v_form" : v_form,
    }
    return render(request, "accounts/register-vendor.html", context)

def user_login(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are already logged In!")
        return redirect("accounts:my-account")
    
    elif request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = auth.authenticate(email=email, password=password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, "You are logged in Successfully!")
            return redirect("accounts:my-account")
        else:
            messages.error(request, "Invalid Credentials! Please try Again")
            return redirect("accounts:user-login")
    return render(request, "accounts/login.html")

def activate_account(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Your Account has successfully activated!")
        return redirect('accounts:my-account')
    else:
        messages.error(request, "Invalid Activation Link!")
        return redirect('accounts:my-account')

def user_logout(request):
    auth.logout(request)
    messages.info(request, "You are logged out successfully! Please Login Again!")
    return redirect("accounts:user-login")

@login_required(login_url="accounts:user-login")
def myAccount(request):
    user = request.user
    redirectUrl = detectUser(user)
    return redirect(redirectUrl)

@login_required(login_url="accounts:user-login")
@user_passes_test(detect_customer_user)
def custDashboard(request):
    return render(request, "accounts/customer-dashboard.html")

@login_required(login_url="accounts:user-login")
@user_passes_test(detect_vendor_user)
def venDashboard(request):
    vendor = Vendor.objects.get(user=request.user)
    context = {
        "vendor" : vendor,
    }
    return render(request, "accounts/vendor-dashboard.html", context)

def forgot_password(request):
    if request.method == "POST":
        email = request.POST.get('email')

        if User.objects.filter(email=email).exists():
            user = User.objects.get(email__exact=email)

            # send password reset_email
            mail_subject = "Resest Your Password"
            email_template = "accounts/emails/reset-password-email.html"
            send_email_verification(request, user, mail_subject, email_template)

            messages.success(request, "Password Reset Link has been sent!")
            return redirect("accounts:user-login")
        else:
            messages.warning(request, "Account Doesn't Exist!")
            return redirect("accounts:user-login")
    return render(request, "accounts/forgot-password.html")

def reset_password_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, "Please Reset your password")
        return redirect('accounts:reset-password')
    else:
        messages.info(request, "This link has been expired!")
        return redirect('accounts:my-account')

def reset_password(request):
    if request.method == "POST":
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        if password == confirm_password:
            pk = request.session.get('uid')
            user = User.objects.get(pk=pk)
            user.set_password(password)
            user.is_active = True
            user.save()
            messages.success(request, "Password Reset Successfull!")
            return redirect('accounts:user-login')
        else:
            messages.warning(request, "Password Mis-Match!!")
            return redirect('accounts:reset-password')
    return render(request, "accounts/reset-password.html")

templates/accounts/customer-dashboard.html
{% extends "partials/base.html" %}
{% load static %}
{% block content %}
{% include "includes/alerts.html" %}
<!-- Main Section Start -->
<div class="main-section">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <!--Load Messages Here-->
            {% include "includes/alerts.html" %}
        </div>
    </div>
    <div class="page-section restaurant-detail-image-section" style=" background: url({% static 'assets/extra-images/cover-photo-1.png' %}) no-repeat scroll 0 0 / cover;">
        <!-- Container Start -->
        <div class="container">
            <!-- Row Start -->
            <div class="row">
                <!-- Column Start -->
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="company-info-detail">
                        <div class="company-info">
                            <div class="img-holder">
                                <figure>
                                    <img src="{% static 'assets/extra-images/listing-logo18.png' %}" alt="">
                                </figure>
                            </div>

                            <div class="text-holder">
                                <span class="restaurant-title">Restaurant Demo</span>
                                <div class="text">
                                    <i class="icon-location"></i>
                                    <p>Mark ricardo road, lane 27, Austin, Texas, USA.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Column End -->
            </div>
            <!-- Row End -->
        </div>
        <!-- Container End -->
    </div>
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    {% include "includes/c_sidebar.html" %}
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="row">
                                    <div class="element-title has-border right-filters-row">
                                        <h5>Recent Orders</h5>
                                        <div class="right-filters row pull-right">
                                            <div class="col-lg-6 col-md-6 col-xs-6">
                                                <div class="input-field">
                                                    <select class="chosen-select-no-single">
                                                        <option selected="selected" value="">Select Orders Status</option>
                                                        <option value="Processing">Processing</option>
                                                        <option value="Cancelled">Cancelled</option>
                                                        <option value="Completed">Completed</option>
                                                    </select>
                                                </div>
                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="user-orders-list">
                                        <div class="responsive-table">
                                            <ul class="table-generic">
                                                <li class="order-heading-titles">
                                                    <div>Order id</div>
                                                    <div>Date</div>
                                                    <div>Total Price</div>
                                                    <div>Charges</div>
                                                    <div>Received</div>
                                                    <div>Status</div>
                                                </li>
                                                <li class="order-heading-titles">
                                                    <div><a href="#" data-toggle="modal" data-target="#order-det-22606">order-22606</a></div>
                                                    <div>Apr 9,2020</div>
                                                    <div>£ 38.99</div>
                                                    <div>£ 3.90</div>
                                                    <div>£ 35.09</div>
                                                    <div><span class="order-status" style="background-color: #047a06;">Completed</span></div>
                                                </li>
                                                
                                                
                                                
                                                <li class="order-heading-titles">
                                                    <div><a href="#" data-toggle="modal" data-target="#order-det-22606">order-22583</a></div>
                                                    <div>Apr 9,2020</div>
                                                    <div>£ 26.22</div>
                                                    <div>£ 2.62</div>
                                                    <div>£ 23.60</div>
                                                    <div><span class="order-status" style="background-color: #1e73be;">Processing</span></div>
                                                </li>
                                                <li class="order-heading-titles">
                                                    <div><a href="#" data-toggle="modal" data-target="#order-det-22606">order-22493</a></div>
                                                    <div>Apr 2,2020</div>
                                                    <div>£ 28.24</div>
                                                    <div>£ 2.82</div>
                                                    <div>£ 25.42</div>
                                                    <div><span class="order-status" style="background-color: #047a06;">Completed</span></div>
                                                </li>
                                            </ul>

                                        </div>												
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->

{% endblock content %}

templates/accounts/forgot-password.html
{% extends "partials/base.html" %}
{% block content %}
<!-- Main Section Start -->
<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                            <div class="user-dashboard loader-holder" style="width:450px; min-height:auto;">
                                <div class="user-holder">
                            <h4 class="text-center" style="margin-bottom: 0;">Forgot Password?</h4>
                            <p class="text-center">Enter Your Email, We will send you the reset-password Link.</p>
                            <hr>
                            <div id="restaurant-sets-holder">
                                <form class="form-fields-set foodbakery-dev-restaurant-form" method="post" action="{% url 'accounts:forgot-password' %}">
                                    {% csrf_token %}
                                    <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                        <li>
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="row">
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Email</label>
                                                                <input type="email" name="email" placeholder="Please enter your Email">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li>
                                            <ul class="errorList">
                                                {% for field in form %}
                                                    {% if field.errors %}
                                                        {% for error in field.errors %}
                                                            <li style="color:red">{{error}}</li>
                                                        {% endfor %}
                                                    {% endif %}
                                                {% endfor %}
                                                <li style="color:red">{{form.non_field_errors}}</li>
                                            </ul>
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="field-holder">
                                                        <div class="payment-holder">
                                                            <input type="submit" value="Submit" id="btn-next-restaurant-information" class="bgcolor">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <!--Load Messages Here-->
                                                    {% include "includes/alerts.html" %}
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
{% endblock content %}

templates/accounts/vendor-dashboard.html
{% extends "partials/base.html" %}
{% block content %}

<h3>Welcome {{user.username}}</h3>
<h4>Role: {{user.get_role}}</h4>
{% include "includes/alerts.html" %}

{% endblock content %}