accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.myAccount),
    path("register-user/", views.registerUser, name="register-user"),
    path("register-vendor/", views.registerVendor, name="register-vendor"),
    path("login/", views.user_login, name="user-login"),
    path("logout/", views.user_logout, name="user-logout"),
    path("myAccount/", views.myAccount, name="my-account"),
    path("customer-dashboard/", views.custDashboard, name="customer-dashboard"),
    path("vendor-dashboard/", views.venDashboard, name="vendor-dashboard"),

    #email Verification
    path('activate/<uidb64>/<token>/', views.activate_account, name="activate"),

    #Forgot Password Links
    path('forgot-password/', views.forgot_password, name="forgot-password"),
    path('reset-password-validate/<uidb64>/<token>/', views.reset_password_validate, name="reset-password-validate"),
    path('reset-password/', views.reset_password, name="reset-password"),

    #Vendor Path
    path('vendor/', include('vendor.urls'), name="vendor"),
]

foodOnline_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as marketplaceviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('', include('accounts.urls'), name="accounts"),
    path('marketplace/', include('marketplace.urls'), name="marketplace"),
    path('cart/', marketplaceviews.cart, name="cart"),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

marketplace/urls.py
from django.urls import path
from . import views

app_name = 'marketplace'

urlpatterns = [
    path('', views.marketplace, name='marketplace'),
    path('<slug:vendor_slug>/', views.vendor_details, name='vendor-details'),

    #Add to Cart
    path('add-to-cart/<int:fooditem_id>/', views.add_to_cart, name='add-to-cart'),
    #Decrease Quantity
    path('decrease-qty/<int:fooditem_id>/', views.decrease_qty, name='decrease-qty'),
    #Delete cart item
    path('delete-cart-item/<int:item_id>/', views.delete_cart_item, name='delete-cart-item'),
]

marketplace/models.py
from django.db import models
from accounts.models import User
from menu.models import FoodItem

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fooditem = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.user

marketplace/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from .context_processors import get_cart_counter, get_cart_amounts
from .models import Cart
from vendor.models import Vendor
from menu.models import Category, FoodItem
from django.db.models import Prefetch
from django.contrib.auth.decorators import login_required

# Create your views here.
def marketplace(request):
    vendors = Vendor.objects.filter(is_approved=True, user__is_active=True)
    vendor_count = vendors.count()
    context = {
        'vendors': vendors,
        'vendor_count': vendor_count,
    }
    return render(request, "marketplace/listings.html", context)

def vendor_details(request, vendor_slug):
    vendor = get_object_or_404(Vendor, vendor_slug=vendor_slug)
    # Get the Cart items of the user and pass to the template
    if request.user.is_authenticated:
        cart_items = Cart.objects.filter(user=request.user)
    else:
        cart_items = None
    # For just the categories of the vendor
    # categories = Category.objects.filter(vendor=vendor)
    # For all categories and their related fooditems by using prefetch_related. We are using reverse lookup here.
    categories = Category.objects.prefetch_related(Prefetch('fooditem', queryset = FoodItem.objects.filter(is_available=True))).filter(vendor=vendor)
    context = {
        'vendor': vendor,
        'categories': categories,
        'cart_items': cart_items,
    }
    return render(request, "marketplace/vendor-details.html", context)

def add_to_cart(request, fooditem_id):
    if request.user.is_authenticated:
        if request.headers.get('X_REQUESTED_WITH') == 'XMLHttpRequest':
            #Check if fooditem exists
            try:
                fooditem = FoodItem.objects.get(id=fooditem_id)
                # Check if the user has already added this fooditem to the cart
                try:
                    cart = Cart.objects.get(user=request.user, fooditem=fooditem)
                    # Increase the quantity of the fooditem in the cart
                    cart.quantity += 1
                    cart.save()
                    return JsonResponse({'status': 'Success', 'message': 'Increased quantity of FoodItem in cart!', 'counter': get_cart_counter(request), 'qty': cart.quantity, 'cart_amounts': get_cart_amounts(request)})
                except:
                    cart = Cart(user=request.user, fooditem=fooditem, quantity=1)
                    cart.save()
                    return JsonResponse({'status': 'Success', 'message': 'FoodItem added to cart!', 'counter': get_cart_counter(request), 'qty': cart.quantity, 'cart_amounts': get_cart_amounts(request)})
            except:
                return JsonResponse({'status': 'Failed', 'message': 'FoodItem does not exist!'})
        else:
            return JsonResponse({'status': 'Failed', 'message': 'Invalid Request!'})
    else:
        return JsonResponse({'status': 'login_required', 'message': 'User is not Logged In!'})
    
def decrease_qty(request, fooditem_id):
    if request.user.is_authenticated:
        if request.headers.get('X_REQUESTED_WITH') == 'XMLHttpRequest':
            #Check if fooditem exists
            try:
                fooditem = FoodItem.objects.get(id=fooditem_id)
                # Check if the user has already added this fooditem to the cart
                try:
                    cart = Cart.objects.get(user=request.user, fooditem=fooditem)
                    # Decrease the quantity of the fooditem in the cart only if there is item greater than 1
                    if cart.quantity > 1:
                        cart.quantity -= 1
                        cart.save()
                    else:
                        cart.delete()
                        cart.quantity = 0
                    return JsonResponse({'status': 'Success', 'message': 'Decreased quantity of FoodItem in cart!', 'counter': get_cart_counter(request), 'qty': cart.quantity, 'cart_amounts': get_cart_amounts(request)})
                except:
                    return JsonResponse({'status': 'Failed', 'message': 'You do not have this item in your cart!'})
            except:
                return JsonResponse({'status': 'Failed', 'message': 'FoodItem does not exist!'})
        else:
            return JsonResponse({'status': 'Failed', 'message': 'Invalid Request!'})
    else:
        return JsonResponse({'status': 'login_required', 'message': 'User is not Logged In!'})

@login_required(login_url='/login/')    
def cart(request):
    cart_items = Cart.objects.filter(user=request.user).order_by('created_at')
    context = {
        'cart_items': cart_items,
    }
    return render(request, "marketplace/cart.html", context)

def delete_cart_item(request, item_id):
    if request.user.is_authenticated:
        if request.headers.get('X_REQUESTED_WITH') == 'XMLHttpRequest':
            try:
                cart_item = Cart.objects.get(id=item_id)
                cart_item.delete()
                return JsonResponse({'status': 'Success', 'message': 'Cart Item Deleted!', 'counter': get_cart_counter(request),'cart_amounts': get_cart_amounts(request)})
            except:
                return JsonResponse({'status': 'Failed', 'message': 'Cart Item does not exist!'})
        else:
            return JsonResponse({'status': 'Failed', 'message': 'Invalid Request!'})
    else:
        return JsonResponse({'status': 'login_required', 'message': 'User is not Logged In!'})


templates/marketplace/cart.html
{% extends "partials/base.html" %}
{% block content %}
<!-- Main Section Start -->
<div class="main-section pt-5">
    <div class="page-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="tabs-holder horizontal">
                        <ul class="stickynav-tabs nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#"><i class="fas fa-shopping-cart text-danger"></i>Cart Items</a></li>
                        </ul>
                        <div class="text-center p-5" id="empty-cart" style="display:none;">
                            <h4>No Food Items Available.</h4>
                        </div>
                        <div class="tab-content">
                            <div id="home" class="tab-pane in active">
                                <div class="menu-itam-holder">
                                    <div id="menu-item-list-6272" class="menu-itam-list">
                                        <ul class="pt-3">
                                            {% if cart_items %}
                                                {% for item in cart_items %}
                                                    <li id="cart-item-{{item.id}}">
                                                        <div class="image-holder"><img src="{{ item.fooditem.image.url }}" alt="{{ item }}"></div>
                                                        <div class="text-holder">
                                                            <h6>{{ item.fooditem }}</h6>
                                                            <span>{{ item.fooditem.description }}</span>
                                                            <a href="{% url 'marketplace:vendor-details' item.fooditem.vendor.vendor_slug %}" class="badge badge-warning">{{item.fooditem.vendor}}</a>
                                                        </div>
                                                        <div class="price-holder">
                                                            <span class="price">${{ item.fooditem.price }}</span>
                                                            <a href="" class="decrease-btn" data-id='{{item.fooditem.id}}' id="{{item.id}}" data-url="{% url 'marketplace:decrease-qty' item.fooditem.id %}" style="margin-right:28px;"><i class="icon-minus text-color"></i></a>
                                                            <label id="qty-{{item.fooditem.id}}">0</label>
                                                            <a href="" class="add-to-cart" data-id='{{item.fooditem.id}}' data-url="{% url 'marketplace:add-to-cart' item.fooditem.id %}"><i class="icon-plus4 text-color"></i></a>
                                                            <a href="" class="delete-cart-item" data-id='{{item.id}}' data-url="{% url 'marketplace:delete-cart-item' item.id %}"><i class="icon-delete text-color"></i></a>
                                                        </div>
                                                    </li>
                                                {% endfor %}
                                            {% else %}
                                                <div class="text-center text-danger p-5">
                                                    <h4>No Food Items Available.</h4>
                                                </div>
                                            {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            {% for item in cart_items %}
                                <span class="item-qty d-none" id="qty-{{item.fooditem.id}}" data-qty="{{item.quantity}}">{{item.quantity}}</span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="tabs-holder horizontal">
                        <ul class="stickynav-tabs nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#"><i class="fas fa-money-check"></i>Your Order</a></li>
                        </ul>
                        <div class="tab-content">
                            <div id="home" class="tab-pane in active">
                                <div class="menu-itam-holder">
                                    <div>
                                        <ul>
                                            <li style="list-style-type:none;">
                                                SUBTOTAL
                                                <span class="price float-right">
                                                    <span class="currency">$</span>
                                                    <span id="subtotal">{{subtotal}}</span>
                                                </span>
                                            </li>
                                            <li style="list-style-type:none;">
                                                TAX
                                                <span class="price float-right">
                                                    <span class="currency">$</span>
                                                    <span id="tax">{{tax}}</span>
                                                </span>
                                            </li>
                                            <li style="list-style-type:none; font-weight:bold;">
                                                TOTAL
                                                <span class="price float-right">
                                                    <span class="currency">$</span>
                                                    <span id="grand-total">{{grand_total}}</span>
                                                </span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
{% endblock content %}

templates/marketplace/listings.html
{% extends 'partials/base.html' %}

{% block content %}
    <!-- Main Section Start -->
		<div class="main-section">
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 10px;margin-bottom: 0px;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="row">
								<aside class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
									
								</aside>
								<div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
									<div class="listing-sorting-holder">
										<div class="row">
											<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
												<h4>{{vendor_count}} Restaurant's found</h4>
											</div>
										</div>
									</div>
									<div class="listing simple">
										<ul>
                                            {% for vendor in vendors %}
                                                <li>
                                                    <div class="img-holder">
                                                        <figure>
                                                            {% if vendor.user_profile.profile_pictures %}
                                                                <a href="{% url 'marketplace:vendor-details' vendor.vendor_slug %}"><img src="{{vendor.user_profile.profile_pictures.url}}" class="img-list wp-post-image" alt=""></a>
                                                            {% else %}
                                                                <a href="#"><img src="assets/default-images/default-profile.png" class="img-list wp-post-image" alt=""></a>
                                                            {% endif %}
                                                        </figure>
                                                        <span class="restaurant-status close"><em class="bookmarkRibbon"></em>Close</span>
                                                    </div>
                                                    <div class="text-holder">
                                                        <div class="post-title">
                                                            <h5>
                                                                <a href="{% url 'marketplace:vendor-details' vendor.vendor_slug %}">{{vendor}}</a>
                                                            </h5>
                                                                <span class="text-mutes">{{vendor.user_profile.address}}</span>
                                                        </div>
                                                    </div>
                                                    <div class="list-option">
                                                        <a href="{% url 'marketplace:vendor-details' vendor.vendor_slug %}" class="viewmenu-btn text-color">View Menu</a>
                                                    </div>
                                                </li>
                                            {% endfor %}
										</ul>
									</div>
									
								</div>
								<div class="section-sidebar col-lg-3 col-md-3 col-sm-12 col-xs-12">
									<div class="message-box" style="background-color: #fa9918;">
										<strong>I'm not Listed!</strong><span>is your restaurant or
											business not
											listed on over site</span>
										<a href="{% url 'accounts:register-vendor' %}" class="request-btn">Add Your business!</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Main Section End -->
{% endblock %}

templates/marketplace/vendor-details.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <!-- Main Section Start -->
			<div class="main-section">
				<div class="page-section restaurant-detail-image-section" style=" background: url({% if vendor.user_profile.cover_photo %} {{vendor.user_profile.cover_photo.url}} {% else %} {% static 'assets/default-images/default-cover.png' %} {% endif %}) no-repeat scroll 0 0 / cover;">
					<!-- Container Start -->
					<div class="container">
						<!-- Row Start -->
						<div class="row">
							<!-- Column Start -->
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
								<div class="company-info-detail">
									<div class="company-info">
										<div class="img-holder">
											<figure>
                                                {% if vendor.user_profile.profile_pictures %}
                                                    <a href="#"><img src="{{vendor.user_profile.profile_pictures.url}}" class="img-list wp-post-image" alt=""></a>
                                                {% else %}
                                                    <a href="#"><img src="assets/default-images/default-profile.png" class="img-list wp-post-image" alt=""></a>
                                                {% endif %}
                                            </figure>
										</div>
										<div class="text-holder">
											<span class="restaurant-title">{{vendor}}</span>
											<div class="text">
                                                <i class="fas fa-map-marker-alt"></i>
												<span>{{vendor.user_profile.address}}</span>
											</div>
										</div>
									</div>
									<div class="delivery-timing reviews-sortby">
										
										<ul>
											<li>
												<a href="#" class="reviews-sortby-active">
													<span>Today :</span>
													11:00 am - 11:00 pm <i class="icon-chevron-small-down"></i>
												</a>
												<ul class="delivery-dropdown">
													<li><a href="#"><span class="opend-day">Monday</span> <span class="opend-time"><small>:</small> 11:00 am - 11:00
																pm</span></a></li>
													<li><a href="#"><span class="opend-day">Tuesday</span> <span class="opend-time"><small>:</small> 11:00 am - 11:00
																pm</span></a></li>
													<li><a href="#"><span class="opend-day">Wednesday</span> <span class="opend-time"><small>:</small> 11:00 am - 11:00
																pm</span></a></li>
													<li><a href="#"><span class="opend-day">Thursday</span> <span class="opend-time"><small>:</small> 11:00 am - 11:00
																pm</span></a></li>
													<li><a href="#"><span class="opend-day">Friday</span> <span class="opend-time"><small>:</small> 11:00 am - 11:00
																pm</span></a></li>
													<li><a href="#"><span class="opend-day">Saturday</span> <span class="opend-time"><small>:</small> 11:00 am - 11:00
																pm</span></a></li>
													<li><a href="#"><span class="opend-day">Sunday</span> <span class="opend-time close-day"><small>:</small>Closed</span></a>
													</li>
												</ul>
											</li>
										</ul>
									</div>
								</div>
							</div>
							<!-- Column End -->
						</div>
						<!-- Row End -->
					</div>
					<!-- Container End -->
				</div>

				<div class="page-section">
					<div class="container">
						<div class="row">
							<div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 sticky-sidebar">
								<div class="filter-wrapper">
									<div class="categories-menu">
										<h6><i class="icon-restaurant_menu"></i>Categories</h6>
										<ul class="menu-list">
                                            {% for category in categories %}
											<li class="active"><a href="#" class="menu-category-link"> {{category}} </a></li>
                                            {% endfor %}
										</ul>
									</div>
								</div>
							</div>
							<div class="col-lg-9 col-md-9 col-sm-8 col-xs-12">
								<div class="tabs-holder horizontal">
									<ul class="stickynav-tabs nav nav-tabs">
										<li class="active"><a data-toggle="tab" href="#home"><i class="icon- icon-room_service"></i>Menu</a></li>
										
									</ul>
									<div class="tab-content">
										<div id="home" class="tab-pane in active">
											<div class="menu-itam-holder">
												<div id="menu-item-list-6272" class="menu-itam-list">
                                                    {% for category in categories %}
                                                        <div class="element-title" id="menu-category-2">
                                                            <h5 class="text-color">{{category}}</h5>
                                                            <span>{{category.description}}</span>
                                                        </div>
                                                        <ul>
                                                            {% if category.fooditem.exists %}
                                                                {% for food in category.fooditem.all %}
                                                                    <li>
                                                                        <div class="image-holder"><img src="{{ food.image.url }}" alt=""></div>
                                                                        <div class="text-holder">
                                                                            <h6>{{ food }}</h6>
                                                                            <span>{{ food.description }}</span>
                                                                        </div>
                                                                        <div class="price-holder">
                                                                            <span class="price">${{ food.price }}</span>
                                                                            <a href="" class="decrease-btn" data-id='{{food.id}}' data-url="{% url 'marketplace:decrease-qty' food.id %}" style="margin-right:28px;"><i class="icon-minus text-color"></i></a>
																			<label id="qty-{{food.id}}">0</label>
                                                                            <a href="" class="add-to-cart" data-id='{{food.id}}' data-url="{% url 'marketplace:add-to-cart' food.id %}"><i class="icon-plus4 text-color"></i></a>
                                                                        </div>
                                                                    </li>
                                                                {% endfor %}
                                                            {% else %}
                                                                <div class="text-center text-danger">
                                                                    <h4>No Food Items Available for <span class="text-muted">{{category}}</span>.</h4>
                                                                </div>
                                                            {% endif %}
                                                        </ul>
                                                    {% endfor %}
												</div>
											</div>
										</div>
										{% for item in cart_items %}
											<span class="item-qty d-none" id="qty-{{item.fooditem.id}}" data-qty="{{item.quantity}}">{{item.quantity}}</span>
										{% endfor %}
									</div>
								</div>
							</div>
							
						</div>
					</div>
				</div>
			</div>
			<!-- Main Section End -->
{% endblock content %}