accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.myAccount),
    path("register-user/", views.registerUser, name="register-user"),
    path("register-vendor/", views.registerVendor, name="register-vendor"),
    path("login/", views.user_login, name="user-login"),
    path("logout/", views.user_logout, name="user-logout"),
    path("myAccount/", views.myAccount, name="my-account"),
    path("customer-dashboard/", views.custDashboard, name="customer-dashboard"),
    path("vendor-dashboard/", views.venDashboard, name="vendor-dashboard"),

    #email Verification
    path('activate/<uidb64>/<token>/', views.activate_account, name="activate"),

    #Forgot Password Links
    path('forgot-password/', views.forgot_password, name="forgot-password"),
    path('reset-password-validate/<uidb64>/<token>/', views.reset_password_validate, name="reset-password-validate"),
    path('reset-password/', views.reset_password, name="reset-password"),

    #Vendor Path
    path('vendor/', include('vendor.urls'), name="vendor"),
]

foodOnline_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as marketplaceviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('', include('accounts.urls'), name="accounts"),
    path('marketplace/', include('marketplace.urls'), name="marketplace"),
    path('cart/', marketplaceviews.cart, name="cart"),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

marketplace/urls.py
from django.urls import path
from . import views

app_name = 'marketplace'

urlpatterns = [
    path('', views.marketplace, name='marketplace'),
    path('<slug:vendor_slug>/', views.vendor_details, name='vendor-details'),

    #Add to Cart
    path('add-to-cart/<int:fooditem_id>/', views.add_to_cart, name='add-to-cart'),
    #Decrease Quantity
    path('decrease-qty/<int:fooditem_id>/', views.decrease_qty, name='decrease-qty'),
    #Delete cart item
    path('delete-cart-item/<int:item_id>/', views.delete_cart_item, name='delete-cart-item'),
]

templates/includes/alerts.html
{% for message in messages %}
<div class="alert alert-{{ message.tags }} show-notification mb-0 alert-dismissible fade show" role="alert">
  <strong>Message: </strong> {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
</div>
{% endfor %}

templates/includes/c_sidebar.html
<div class="user-account-nav user-account-sidebar">
    <div class="user-nav-list">
        <ul>
            <li class="active"><a href="{% url 'accounts:my-account' %}"><i class="icon-dashboard3"></i>Dashboard</a></li>
            <li><a href="restaurant-restaurant.html"><i class="icon-add_shopping_cart"></i>My Orders</a></li>
            <li><a href="restaurant-menu-builder.html"><i class="icon-build"></i>Profile Settings</a></li>
            <li><a href="restaurant-change-password.html"><i class="icon-unlock-alt"></i>Change Password</a></li>
            <li><a class="logout-btn" href="registration.html"><i class="icon-log-out"></i>Signout</a></li>
        </ul>
    </div>
</div>

templates/includes/cover.html
{% load static %}
<div class="page-section restaurant-detail-image-section" style=" background: url({% if vendor.user_profile.cover_photo %} {{vendor.user_profile.cover_photo.url}} {% else %} {% static 'assets/default-images/default-cover.png' %} {% endif %}) no-repeat scroll 0 0 / cover;">
    <!-- Container Start -->
    <div class="container">
        <!-- Row Start -->
        <div class="row">
            <!-- Column Start -->
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="company-info-detail">
                    <div class="company-info">
                        <div class="img-holder">
                            <figure>
                                {% if vendor.user_profile.profile_pictures %}
                                <img src="{{vendor.user_profile.profile_pictures.url}}" alt="Profile Image">
                                {% else %}
                                <img src="{% static 'assets/default-images/default-profile.png' %}" alt="Profile Image">
                                {% endif %}
                            </figure>
                        </div>

                        <div class="text-holder">
                            <span class="restaurant-title">{{vendor.vendor_name}}</span>
                            <div class="text">
                                <i class="icon-location"></i>
                                {% if vendor.user_profile.address %}
                                    <p>{{vendor.user_profile.address}}</p>
                                {% else %}
                                    <p>Home 123, St.123 , City</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Column End -->
        </div>
        <!-- Row End -->
    </div>
    <!-- Container End -->
</div>

templates/includes/footer.html
{% load static %}
<!-- Footer Start -->
<footer id="footer" class="footer-style-2">
    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="widget widget-newsletter">
                        <div class="widget-title">
                            <h5>Subscribe to our Newsletter</h5>
                        </div>
                        <div class="fieldset">
                            <form action="#">
                                <div class="field-holder">
                                    <label>
                                        <i class=" icon-envelope3"></i>
                                        <input type="text" class="field-input" placeholder=" Enter Your Email Address...">
                                    </label>
                                </div>
                                <div class="field-holder btn-holder">
                                    <input class="subscribe-btn bgcolor" type="submit" value="Sign Up">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright-sec">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="copyright-inner">
                        <div class="copy-right">
                            <p>© 2020 Foodbakery. All Rights Reserved. Developed By <a href="#">Rathan Kumar</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- /.cs-copyright -->
</footer>
<!-- Footer End -->
</div>

<!-- Modal Popup End -->
<script src="{% static 'assets/js/scripts.js' %}"></script>
<script src="{% static 'assets/js/functions.js' %}"></script>
</body>

</html>

templates/includes/navbar.html
{% load static %}
<!--Main Wrapper-->
<div class="wrapper">
    <!-- Header Start -->
    <header id="header">
        <div class="main-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                        <div class="logo">
                            <figure>
                                <a href="{% url 'home' %}" class="light-logo">
                                    <img src="{% static 'assets/logo/foodOnlineLogo.png' %}" alt="FoodBakery" width="230px">
                                </a>
                            </figure>
                        </div>
                        <div class="main-location ml-4">
                            <ul>
                                <li class="location-has-children choose-location">
                                    <form action="#">
                                        <input type="text" value="" name="location" placeholder="Enter your delivery location" autocomplete="off">
                                        <span id="foodbakery_radius_location_open" class="foodbakery-radius-location"><i class="icon-target5"></i></span>
                                    </form>
                                    
                                </li>
                            </ul>
                            </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div class="login-option">
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'cart' %}">
                                    <i class="fas fa-shopping-cart text-danger" style="font:22px;"></i>
                                    <span class="badge badge-warning" id="cart_counter" style="border-radius:50px; position:relative; bottom:10px; left: -5px;">{{ cart_count }}</span>
                                </a>
                            {% endif %}
                                <a href="{% url 'marketplace:marketplace' %}" class="btn btn-outline-danger text-uppercase">Marketplace</a>
                            {% if user.is_authenticated %}
                                <a class="cs-color cs-popup-joinus-btn login-popup" href="{% url 'accounts:my-account' %}">My Account</a>
                                <a class="cs-color cs-popup-joinus-btn login-popup text-danger" href="{% url 'accounts:user-logout' %}">Logout</a>
                            {% else %}
                                <a class="cs-color cs-popup-joinus-btn login-popup" href="{% url 'accounts:user-login' %}">Login</a> / 
                                    <span><a href="{% url 'accounts:register-user' %}" class="cs-color cs-popup-joinus-btn login-popup ml-0">Register</a></span>
                                <a class="get-start-btn" href="{% url 'accounts:register-vendor' %}">
                                    Register
                                    Restaurant </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header End -->

templates/includes/v_sidebar.html
<div class="user-account-nav user-account-sidebar">
    <div class="user-nav-list">
        <ul>
            <li class="{% if request.resolver_match.url_name == 'vendor-dashboard' %}active{% endif %}"><a href="{% url 'accounts:my-account' %}"><i class="icon-dashboard3"></i>Dashboard</a></li>
            <li class="{% if request.resolver_match.url_name == 'restaurant-profile' %}active{% endif %}"><a href="{% url 'accounts:vendor:restaurant-profile' %}"><i class="icon-building"></i>My Restaurant</a></li>
            <li class="{% if request.resolver_match.url_name == 'menu-builder' %}active{% endif %}"><a href="{% url 'accounts:vendor:menu-builder' %}"><i class="icon-menu5"></i>Menu Builder</a></li>
            <li><a href="restaurant-orders.html"><i class="icon-add_shopping_cart"></i>Orders</a></li>
            <li><a href="restaurant-earnings.html"><i class="icon-money"></i>Earnings</a></li>
            <li><a href="restaurant-statement.html"><i class="icon-file-text22"></i>Statement</a></li>
            <li><a href="restaurant-change-password.html"><i class="icon-unlock-alt"></i>Change Password</a></li>
            <li><a class="logout-btn" href="registration.html"><i class="icon-log-out"></i>Signout</a></li>
        </ul>
    </div>
</div>